# fly.toml app configuration file generated for haveri-app on 2026-02-08T12:09:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haveri-app'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'npm run db:migrate'

[env]
  HOST = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3000'

[processes]
  web = 'node build'
  worker = 'npm run worker'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
